### ISSUE TITLE
Git SSH cloning fails

### ISSUE THREAD

**Issue by Vlaaaaaaad** [hashicorp/terraform-github-actions#39] opened 2019-08-13 11:30 UTC
When using the `init` action as defined below:
```
name: Terraform

on: [push]

jobs:

  Formatting:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Formatting
      uses: hashicorp/terraform-github-actions/fmt@v0.3.5

  Validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Init
      uses: hashicorp/terraform-github-actions/init@v0.3.5
    
    - name: Validation
      uses: hashicorp/terraform-github-actions/validate@v0.3.5
      env:
        AWS_DEFAULT_REGION: us-east-1
```
the `init` step fails due to not being able to clone the repo:
```
[DEBUG] Using modified User-Agent: Terraform/0.12.6 terraform-github-actions/1.0
Initializing modules...
Downloading git@github.com:terraform-aws-modules/terraform-aws-eks.git?ref=v5.0.0 for eks...

Error: Failed to download module

Could not download module "eks" (eks.tf:1) source code from
"git@github.com:terraform-aws-modules/terraform-aws-eks.git?ref=v5.0.0": error
downloading
'ssh://git@github.com/terraform-aws-modules/terraform-aws-eks.git?ref=v5.0.0':
/usr/bin/git exited with 128: Cloning into '.terraform/modules/eks'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any ideas about how this could be fixed? 

The npm action has [a comment suggesting some bash magic to insert SSH keys](https://github.com/actions/npm/issues/25#issuecomment-486818213). Maybe something along these lines?

I am new to GitHub actions so I may be totally missing something.

**Comment by sudomateo** [comment] 2019-09-18 04:01
So this is not an issue necessarily. SSH operations will fail if there are no private SSH keys on the container being used. Adding an option to inject an SSH private key into the container isn't necessarily out of the question, but would definitely take away from the scope of this project. Then dealing within encrypted private SSH keys also becomes a concern.

**Comment by abatilo** [comment] 2019-09-19 01:23
Shouldn't ssh key injection be in scope? Otherwise it'll be impossible to do an init when you have an SSH sourced module.

**Comment by sudomateo** [comment] 2019-09-19 01:45
@abatilo I never said it was out of scope, only that it will take away from the scope of this project. If it was possible to use GitHub Actions inputs inside the `Dockerfile`, implementing this would be trivial. Since that's not the case, implementing this will require writing extra code to handle SSH private key injection and decrypting the SSH private key if it's encrypted. It's something that will be considered, but there are other issues that I believe should be tackled first. If you have time to work on this, pull requests would be appreciated.

**Comment by abatilo** [comment] 2019-09-19 02:00
Oh! I'm sorry, I misinterpreted what you meant by "taking away scope". I'd love to contribute if I could get a little guidance on what needs to be done

**Comment by Vlaaaaaaad** [comment] 2019-09-19 08:14
Some notes on this since I kept working:
- Docker-based GitHub Actions are sloooooow. Since there's no caching they are so so slow. It's better to just install Terraform yourself and use it like that
- there are actions that load SSH keys from GitHub Secrets and that even expose it to Docker if you are using it( SSH_AGENT_SOCK)

All these things and other learnings will be shared in an open-source repo sometime soon™️( I wanted to do it this week but other things got in the way).

**Comment by Vlaaaaaaad** [comment] 2019-09-27 08:38
Scratch that, I found no way to get the `SSH_AGENT_SOCK` to work. Not manually, nor with [webfactory/ssh-agent@v0.1.1](https://github.com/marketplace/actions/webfactory-ssh-agent).

I am going forward with manual SSH setup + Terraform install for all repos that require private modules.

**Comment by thorker** [comment] 2019-09-27 11:29
@Vlaaaaaaad 
I think the problem is the missing possibility to extend prepared docker actions with volumes, so  you can inject your ssh_auth_sock and set the env var to the mounted volume.

I am waiting for this feature to be implemented by GitHub.

**Comment by abatilo** [comment] 2019-09-27 12:23
This is what I ended up doing to clone a private module, and it definitely worked even if a bit wonky.
```
    - name: Create .ssh directory
      uses: actions/bin/sh@master
      with:
        args: '"mkdir -p $HOME/.ssh"'
    - name: Write SSH key to disk
      uses: actions/bin/sh@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: '"echo \"$SSH_PRIVATE_KEY\" > $HOME/.ssh/id_rsa"'
    - name: Set SSH key permissions
      uses: actions/bin/sh@master
      with:
        args: '"chmod 400 $HOME/.ssh/id_rsa"'
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"
        TF_ACTION_WORKING_DIR: ${{ matrix.folders }}
```

**Comment by Vlaaaaaaad** [comment] 2019-09-27 13:00
I just went full retro since I don't really want to set `StrictHostKeyChecking=no`:

```yml
steps:
  - name: Clone repo
    uses: actions/checkout@master
    with:
      fetch-depth: 1

  - name: Setup SSH Keys and known_hosts
    env:
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #  Copied from https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
    run: |
      SSH_PATH="$HOME/.ssh"

      mkdir -p "$SSH_PATH"
      touch "$SSH_PATH/known_hosts"

      echo "$PRIVATE_KEY" > "$SSH_PATH/id_rsa"

      chmod 700 "$SSH_PATH"
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      chmod 600 "$SSH_PATH/known_hosts"
      chmod 600 "$SSH_PATH/id_rsa"

      eval $(ssh-agent)
      ssh-add "$SSH_PATH/id_rsa"

  - name: Install Terraform
    run: |
      curl -LO https://raw.github.com/robertpeteuil/terraform-installer/master/terraform-install.sh
      chmod +x terraform-install.sh
      ./terraform-install.sh -a
      rm terraform-install.sh

  - name: Terraform init
    run: |
      terraform init
```

**Comment by alexbde** [comment] 2019-12-05 16:06
Hi all, I stumbled upon same issue. Here's a minimal example of what I did with webfactory/ssh-agent: https://github.com/alexbde/terraform-demo/pull/7/checks

I'm pushing this issue again because (as you can see from log) `git clone` via command line works well while `terraform init` fails. I know alexbde/terraform-demo is not a private repo but failure is the same.

@sudomateo Could you please have a look at it? Thank you very much in advance! :)

**Comment by alexbde** [comment] 2019-12-06 09:06
In inheritance of @abatilo and @Vlaaaaaaad here's my dirty workaround:

    - name: Terraform initialize
      uses: hashicorp/terraform-github-actions@v0.6.3
      env:
      GIT_SSH_COMMAND: "echo '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa
        && echo 'github.com ssh-rsa ${{ env.GITHUB_COM_SSH_RSA_PUBLIC_KEY }}' > known_hosts
        && chmod 400 id_rsa known_hosts
        && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
      with:
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: ${{ env.TF_ACTION_WORKING_DIR }}
        tf_actions_comment: true

With `GITHUB_COM_SSH_RSA_PUBLIC_KEY` = `AAAAB3NzaC1yc2E...` (GitHub Public Key received from `$ ssh-keyscan github.com`.

**Comment by JohnWillker** [comment] 2020-02-18 17:43
> In inheritance of @abatilo and @Vlaaaaaaad here's my dirty workaround:
> 
> ```
> - name: Terraform initialize
>   uses: hashicorp/terraform-github-actions@v0.6.3
>   env:
>     GIT_SSH_COMMAND: "echo '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa
>       && echo 'github.com ssh-rsa ${{ env.GITHUB_COM_SSH_RSA_PUBLIC_KEY }}' > known_hosts
>       && chmod 400 id_rsa known_hosts
>       && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
>   with:
>     tf_actions_version: ${{ env.TF_VERSION }}
>     tf_actions_subcommand: 'init'
>     tf_actions_working_dir: ${{ env.TF_ACTION_WORKING_DIR }}
>     tf_actions_comment: true
> ```
> 
> With `GITHUB_COM_SSH_RSA_PUBLIC_KEY` = `AAAAB3NzaC1yc2E...` (GitHub Public Key received from `$ ssh-keyscan github.com`).

This is not working for me, I really need to use private modules via SSH.

**Comment by sudomateo** [comment] 2020-02-18 17:54
@JohnWillker Does your SSH private key have a passphrase? Also are your SSH keys RSA? It seems this example assumes an RSA key pair type with an empty passphrase.

**Comment by JohnWillker** [comment] 2020-02-19 22:33
> @JohnWillker Does your SSH private key have a passphrase? Also are your SSH keys RSA? It seems this example assumes an RSA key pair type with an empty passphrase.

@sudomateo Thanks for the answer.

The SSH private key doesn't have a passphrase and the SSH keys I think is RSA the have a format like: `ssh-rsa AAAAB3N.....` every time the message says my SSH key is invalid but is the same key I have used in Gitlab CI.

I have tried other approaches like:

```yaml
GIT_SSH_COMMAND: "mkdir /root/.ssh
            && ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
            && echo '${{ secrets.GITHUB_ADMIN_SSH_PRIVATE_KEY }}' > /root/.ssh/id_rsa
            && chmod 400 /root/.ssh/id_rsa"
```

Without success.

I don't know how the GIT_SSH_COMMAND works, whatever command insert in this variable will be executed before any other script?

**Comment by alexbde** [comment] 2020-02-24 06:43
> I don't know how the GIT_SSH_COMMAND works, whatever command insert in this variable will be executed before any other script?

It's a git feature: https://git-scm.com/docs/git#Documentation/git.txt-codeGITSSHCOMMANDcode

**Comment by joesteffee** [comment] 2020-03-01 04:26
The solution above works well. I added some additional logic so you don't have to store the public key in secrets:

```
        env:
          GIT_SSH_COMMAND: "echo '${{ secrets.PRIVATE_KEY }}' > id_rsa
            && echo $(ssh-keyscan -t rsa github.com) > known_hosts
            && chmod 400 id_rsa known_hosts
            && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
```

**Comment by iiro** [comment] 2020-03-01 07:16
> > In inheritance of @abatilo and @Vlaaaaaaad here's my dirty workaround:
> > ```
> > - name: Terraform initialize
> >   uses: hashicorp/terraform-github-actions@v0.6.3
> >   env:
> >     GIT_SSH_COMMAND: "echo '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa
> >       && echo 'github.com ssh-rsa ${{ env.GITHUB_COM_SSH_RSA_PUBLIC_KEY }}' > known_hosts
> >       && chmod 400 id_rsa known_hosts
> >       && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
> >   with:
> >     tf_actions_version: ${{ env.TF_VERSION }}
> >     tf_actions_subcommand: 'init'
> >     tf_actions_working_dir: ${{ env.TF_ACTION_WORKING_DIR }}
> >     tf_actions_comment: true
> > ```
> > 
> > 
> > With `GITHUB_COM_SSH_RSA_PUBLIC_KEY` = `AAAAB3NzaC1yc2E...` (GitHub Public Key received from `$ ssh-keyscan github.com`).
> 
> This is not working for me, I really need to use private modules via SSH.

Not that this will probably help you, but my workaround for this is to pull the private modules from TF Enterprise's Module Registry. But ofc, you might not use TFE...

**Comment by kalib** [comment] 2020-03-02 21:19
Any updates? Also not working for me... Tried many options already posted by people here...

This is my latest attempt:

> name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GIT_SSH_COMMAND: "echo '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa
            && echo 'github.com ssh-rsa ${{ env.GITHUB_COM_SSH_RSA_PUBLIC_KEY }}' > known_hosts
            && chmod 400 id_rsa known_hosts
            && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

**Comment by alexbde** [comment] 2020-03-04 07:14
> The solution above works well. I added some additional logic so you don't have to store the public key in secrets

@joesteffee I'm aware of that option but I created public key in a trusted environment and stored it intentionally for extended security. See [OWASP about Public Key Pinning](https://owasp.org/www-community/controls/Certificate_and_Public_Key_Pinning). If you scan public key on demand there will be no MIDM prevention.

**Closed** 2020-05-06 14:56 UTC
