### ISSUE TITLE
Proposal: Use GitHub syntax highlighting in terraform comments

### ISSUE THREAD

**Issue by ericmatte** [hashicorp/terraform-github-actions#162] opened 2020-04-02 16:16 UTC
Hi,

I think that syntax highlighting allows users to see the right information more quickly.
When I manually paste a plan in some markdown, I also chose a language so that the syntax highlighting makes the plan clearer.

I've found that the `js` one is great with terraform plans.

As an example for this change, we would only need to modify that line:
https://github.com/hashicorp/terraform-github-actions/blob/master/src/terraform_plan.sh#L50
to:
```js
\`\`\`js
${planOutput}
\`\`\`
```

This can also work with other available terraform commands like `plan`, `init`, etc.

---

### `terraform plan` dummy example:
**Currently:**
#### `terraform plan` Success
```
  # module.test.policy_attachment will be destroyed
  - resource "aws_iam_role_policy_attachment" "policy_attachment" {
      - id         = "RoleForTest" -> null
      - policy_arn = "arn:aws:iam::aws:policy/AWSRoleForTest" -> null
      - role       = "RoleForTest" -> null
    }
```

**Could be outputted like so:**
#### `terraform plan` Success
```js
  # module.test.policy_attachment will be destroyed
  - resource "aws_iam_role_policy_attachment" "policy_attachment" {
      - id         = "RoleForTest" -> null
      - policy_arn = "arn:aws:iam::aws:policy/AWSRoleForTest" -> null
      - role       = "RoleForTest" -> null
    }
```

**Comment by ericmatte** [comment] 2020-04-08 18:17
**EDIT**: `hcl` should be used for terraform:
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1937

**Comment by sudomateo** [comment] 2020-04-12 21:43
Duplicate of #153. Closing.

**Closed by sudomateo** 2020-04-12 21:43 UTC
